# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent
  namespace: config-management-system
  labels:
    app: opentelemetry
    component: otel-agent
    configmanagement.gke.io/system: "true"
    configmanagement.gke.io/arch: "csmr"
data:
  otel-agent-config.yaml: |
    receivers:
      opencensus:
    exporters:
      opencensus:
        endpoint: otel-collector.config-management-monitoring:55678
        tls:
          insecure: true
    processors:
      batch:
      # Generate resource attributes from metric tags.
      # This is done in the sidecar instead of the reconciler, because
      # attributes are not otherwise mutable after constructing a metrics
      # emitter.
      attributes/sync:
        actions:
          - key: configsync.sync.kind
            action: insert
            from_context: sync_kind
          - key: configsync.sync.name
            action: insert
            from_context: sync_name
          - key: configsync.sync.namespace
            action: insert
            from_context: sync_namespace
          - key: configsync.reconciler.name
            action: insert
            from_context: reconciler_name
    extensions:
      health_check:
    service:
      extensions: [health_check]
      pipelines:
        metrics:
          receivers: [opencensus]
          processors: [batch, attributes/sync]
          exporters: [opencensus]